spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board_tarefas
    username: root
    password: Marrero@#2000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true